sudo: required
services:
  - docker
before_install:
  - docker build -t shashank/docker-react-cicd -f Dockerfile.dev .
script:
  - docker run shashank/docker-react-cicd npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react-cicd"
  env: "DockerReactCicd-env"
  bucket-name: ""
  bucket-path: "docker-react-cicd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"